x-common: &common
  restart: unless-stopped
  environment: &env
    TZ: America/Los_Angeles
    PUID: 1000
    PGID: 1000
  networks:
    - proxy_net
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 3

x-health: &health
  interval: 5m
  timeout: 10s
  retries: 5
  start_period: 1m

# =================================================================
networks:
  proxy_net:
    external: true

# =================================================================
services:
  web:
    <<: *common
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.web
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - app-data:/data
    environment:
      <<: *env
    # ================================
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      <<: *health
    # ================================
    labels:
      # TRAEFIK
      - traefik.enable=true
      # Use the right network and port
      - traefik.docker.network=proxy_net
      - traefik.http.services.guest.loadbalancer.server.port=3000
      # HTTPS by default
      - traefik.http.routers.guest.rule=Host(`guest.lan.goober.house`)
      - traefik.http.routers.guest.entrypoints=websecure
      - traefik.http.routers.guest.tls=true
      - traefik.http.routers.guest.tls.certresolver=cloudflare
      # HTTP redirect to HTTPS
      - traefik.http.routers.guest-http.entrypoints=web
      - traefik.http.routers.guest-http.rule=Host(`guest.lan.goober.house`)
      - traefik.http.routers.guest-http.middlewares=redir-https
      - traefik.http.middlewares.redir-https.redirectscheme.scheme=https

  worker:
    <<: *common
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.worker
    environment:
      <<: *env
      WEB_URL: http://web:3000
    volumes:
      - app-data:/data
      - exports:/exports
    depends_on:
      web:
        condition: service_started

volumes:
  app-data:
  exports:
    driver: local
